unified_metric:
  class_path: comet.models.UnifiedMetric
  init_args:
    nr_frozen_epochs: 0.3
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-05 # 1.0e-06
    learning_rate: 3.1e-05 # 1.5e-05
    layerwise_decay: 0.95
    encoder_model: RoBERTa
    pretrained_model: roberta-large
    sent_layer: mix
    layer_transformation: sparsemax
    word_layer: 24
    loss: mse
    dropout: 0.15
    batch_size: 4
    train_data: 
      - ~/nlprx/lens-salsa/data/simpeval-regression/train.csv
    validation_data: 
      - ~/nlprx/lens-salsa/data/simpeval-regression/valid.csv
    hidden_sizes:
      - 384
      # - 3072
      # - 1024
    activations: Tanh
    input_segments:
      - mt # mt
      - src # src
      # - ref
    loss_lambda: 0.9
    word_level_training: False
    score_target: score
    
trainer: ../trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../model_checkpoint.yaml
